//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 03:13:26 PM EDT 
//


package edu.harvard.libcomm.message;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.libcomm.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.libcomm.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LibCommMessage }
     * 
     */
    public LibCommMessage createLibCommMessage() {
        return new LibCommMessage();
    }

    /**
     * Create an instance of {@link LibCommMessage.History }
     * 
     */
    public LibCommMessage.History createLibCommMessageHistory() {
        return new LibCommMessage.History();
    }

    /**
     * Create an instance of {@link LibCommMessage.Watchers }
     * 
     */
    public LibCommMessage.Watchers createLibCommMessageWatchers() {
        return new LibCommMessage.Watchers();
    }

    /**
     * Create an instance of {@link LibCommMessage.Payload }
     * 
     */
    public LibCommMessage.Payload createLibCommMessagePayload() {
        return new LibCommMessage.Payload();
    }

    /**
     * Create an instance of {@link LibCommMessage.History.Event }
     * 
     */
    public LibCommMessage.History.Event createLibCommMessageHistoryEvent() {
        return new LibCommMessage.History.Event();
    }

    /**
     * Create an instance of {@link LibCommMessage.Watchers.Watcher }
     * 
     */
    public LibCommMessage.Watchers.Watcher createLibCommMessageWatchersWatcher() {
        return new LibCommMessage.Watchers.Watcher();
    }

}
