//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.28 at 12:14:22 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/MARC21/slim", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.loc.marc;
